version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
      - "81:81"
      - "82:82"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./project1:/usr/share/nginx/project1
      - ./project2:/usr/share/nginx/project2
      - ./php-project:/var/www/html  # Project directory
    depends_on:
      - php
    restart: always

  php:
    image: php:8.0-fpm
    container_name: php-fpm
    volumes:
      - ./php-project:/var/www/html
    restart: always
